// ============================================
// PERMISSIONS CONSTANTS
// ============================================

export const PERMISSIONS = {
  // Users
  USERS_VIEW: "users:view",
  USERS_CREATE: "users:create",
  USERS_EDIT: "users:edit",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  USERS_MANAGE: "users:manage",
  
  // Staff Management
  STAFF_VIEW: "staff:view",
  STAFF_CREATE: "staff:create",
  STAFF_EDIT: "staff:edit",
  STAFF_DELETE: "staff:delete",
  STAFF_MANAGE: "staff:manage",
  
  // Portals
  PORTALS_VIEW: "portals:view",
  PORTALS_CREATE: "portals:create",
  PORTALS_EDIT: "portals:edit",
  PORTALS_DELETE: "portals:delete",
  PORTALS_MANAGE: "portals:manage",
  
  // Roles & Permissions
  ROLES_VIEW: "roles:view",
  ROLES_CREATE: "roles:create",
  ROLES_UPDATE: "roles:update",
  ROLES_DELETE: "roles:delete",
  ROLES_MANAGE: "roles:manage",
  
  // Domains
  DOMAINS_VIEW: "domains:view",
  DOMAINS_CREATE: "domains:create",
  DOMAINS_UPDATE: "domains:update",
  DOMAINS_DELETE: "domains:delete",
  DOMAINS_MANAGE: "domains:manage",
  
  // Categories
  CATEGORIES_VIEW: "categories:view",
  CATEGORIES_CREATE: "categories:create",
  CATEGORIES_UPDATE: "categories:update",
  CATEGORIES_DELETE: "categories:delete",
  CATEGORIES_MANAGE: "categories:manage",
  
  // Courses
  COURSES_VIEW: "courses:view",
  COURSES_CREATE: "courses:create",
  COURSES_UPDATE: "courses:update",
  COURSES_DELETE: "courses:delete",
  COURSES_MANAGE: "courses:manage",
  
  // Content (Videos, Materials)
  CONTENT_VIEW: "content:view",
  CONTENT_CREATE: "content:create",
  CONTENT_UPDATE: "content:update",
  CONTENT_DELETE: "content:delete",
  CONTENT_MANAGE: "content:manage",
  
  // Analytics
  ANALYTICS_VIEW: "analytics:view",
  ANALYTICS_EXPORT: "analytics:export",
  
  // Settings
  SETTINGS_VIEW: "settings:view",
  SETTINGS_UPDATE: "settings:update",
  SETTINGS_MANAGE: "settings:manage",
  
  // Database Explorer
  DATABASE_VIEW: "database:view",
  DATABASE_EXECUTE: "database:execute",
  
  // Audit Logs
  AUDIT_VIEW: "audit:view",
  AUDIT_EXPORT: "audit:export",
  
  // Payments
  PAYMENTS_VIEW: "payments:view",
  PAYMENTS_REFUND: "payments:refund",
  PAYMENTS_MANAGE: "payments:manage",
  
  // Subscriptions
  SUBSCRIPTIONS_VIEW: "subscriptions:view",
  SUBSCRIPTIONS_MANAGE: "subscriptions:manage",
  
  // Newsletter
  NEWSLETTER_VIEW: "newsletter:view",
  NEWSLETTER_SEND: "newsletter:send",
  NEWSLETTER_MANAGE: "newsletter:manage",
  
  // Storage
  STORAGE_VIEW: "storage:view",
  STORAGE_UPLOAD: "storage:upload",
  STORAGE_DELETE: "storage:delete",
  STORAGE_MANAGE: "storage:manage",
  
  // Support
  SUPPORT_VIEW: "support:view",
  SUPPORT_RESPOND: "support:respond",
  SUPPORT_MANAGE: "support:manage",
  
  // Certificates
  CERTIFICATES_VIEW: "certificates:view",
  CERTIFICATES_ISSUE: "certificates:issue",
  CERTIFICATES_REVOKE: "certificates:revoke",
  CERTIFICATES_MANAGE: "certificates:manage",
  
  // Plans
  PLANS_VIEW: "plans:view",
  PLANS_CREATE: "plans:create",
  PLANS_UPDATE: "plans:update",
  PLANS_DELETE: "plans:delete",
  PLANS_MANAGE: "plans:manage",

  // Scholarships & Financial Aid
  SCHOLARSHIPS_VIEW: "scholarships:view",
  SCHOLARSHIPS_CREATE: "scholarships:create",
  SCHOLARSHIPS_UPDATE: "scholarships:update",
  SCHOLARSHIPS_DELETE: "scholarships:delete",
  SCHOLARSHIPS_PUBLISH: "scholarships:publish",
  SCHOLARSHIPS_ARCHIVE: "scholarships:archive",
  SCHOLARSHIPS_MANAGE: "scholarships:manage",
  
  // Scholarship Applications
  APPLICATIONS_VIEW: "applications:view",
  APPLICATIONS_REVIEW: "applications:review",
  APPLICATIONS_APPROVE: "applications:approve",
  APPLICATIONS_REJECT: "applications:reject",
  APPLICATIONS_MANAGE: "applications:manage",
  
  // Scholarship Awards
  AWARDS_VIEW: "awards:view",
  AWARDS_CREATE: "awards:create",
  AWARDS_EDIT: "awards:edit",
  AWARDS_CANCEL: "awards:cancel",
  AWARDS_MANAGE: "awards:manage",
  
  // Sponsors
  SPONSORS_VIEW: "sponsors:view",
  SPONSORS_CREATE: "sponsors:create",
  SPONSORS_UPDATE: "sponsors:update",
  SPONSORS_DELETE: "sponsors:delete",
  SPONSORS_MANAGE: "sponsors:manage",
  
  // Financial Aid
  FINANCIAL_AID_VIEW: "financial_aid:view",
  FINANCIAL_AID_CREATE: "financial_aid:create",
  FINANCIAL_AID_UPDATE: "financial_aid:update",
  FINANCIAL_AID_DELETE: "financial_aid:delete",
  FINANCIAL_AID_MANAGE: "financial_aid:manage",
  
  // Scholarship Types
  SCHOLARSHIP_TYPES_VIEW: "scholarship_types:view",
  SCHOLARSHIP_TYPES_CREATE: "scholarship_types:create",
  SCHOLARSHIP_TYPES_UPDATE: "scholarship_types:update",
  SCHOLARSHIP_TYPES_DELETE: "scholarship_types:delete",
  SCHOLARSHIP_TYPES_MANAGE: "scholarship_types:manage",
  
  // Review Rubrics
  RUBRICS_VIEW: "rubrics:view",
  RUBRICS_CREATE: "rubrics:create",
  RUBRICS_UPDATE: "rubrics:update",
  RUBRICS_DELETE: "rubrics:delete",
  RUBRICS_MANAGE: "rubrics:manage",
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

// Default role permissions
export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.DOMAINS_VIEW,
    PERMISSIONS.DOMAINS_CREATE,
    PERMISSIONS.DOMAINS_UPDATE,
    PERMISSIONS.DOMAINS_DELETE,
    PERMISSIONS.DOMAINS_MANAGE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_UPDATE,
    PERMISSIONS.CATEGORIES_DELETE,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_DELETE,
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_MANAGE,
    PERMISSIONS.SUBSCRIPTIONS_VIEW,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.NEWSLETTER_VIEW,
    PERMISSIONS.NEWSLETTER_SEND,
    PERMISSIONS.NEWSLETTER_MANAGE,
    PERMISSIONS.STORAGE_VIEW,
    PERMISSIONS.STORAGE_UPLOAD,
    PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.STORAGE_MANAGE,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.CERTIFICATES_VIEW,
    PERMISSIONS.CERTIFICATES_ISSUE,
    PERMISSIONS.CERTIFICATES_MANAGE,
    PERMISSIONS.PLANS_VIEW,
    PERMISSIONS.PLANS_CREATE,
    PERMISSIONS.PLANS_UPDATE,
    PERMISSIONS.PLANS_DELETE,
    PERMISSIONS.PLANS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    // Scholarships - Full access for admins
    PERMISSIONS.SCHOLARSHIPS_VIEW,
    PERMISSIONS.SCHOLARSHIPS_CREATE,
    PERMISSIONS.SCHOLARSHIPS_UPDATE,
    PERMISSIONS.SCHOLARSHIPS_DELETE,
    PERMISSIONS.SCHOLARSHIPS_PUBLISH,
    PERMISSIONS.SCHOLARSHIPS_ARCHIVE,
    PERMISSIONS.SCHOLARSHIPS_MANAGE,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_REVIEW,
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_REJECT,
    PERMISSIONS.APPLICATIONS_MANAGE,
    PERMISSIONS.AWARDS_VIEW,
    PERMISSIONS.AWARDS_CREATE,
    PERMISSIONS.AWARDS_EDIT,
    PERMISSIONS.AWARDS_CANCEL,
    PERMISSIONS.AWARDS_MANAGE,
    PERMISSIONS.SPONSORS_VIEW,
    PERMISSIONS.SPONSORS_CREATE,
    PERMISSIONS.SPONSORS_UPDATE,
    PERMISSIONS.SPONSORS_DELETE,
    PERMISSIONS.SPONSORS_MANAGE,
    PERMISSIONS.FINANCIAL_AID_VIEW,
    PERMISSIONS.FINANCIAL_AID_CREATE,
    PERMISSIONS.FINANCIAL_AID_UPDATE,
    PERMISSIONS.FINANCIAL_AID_DELETE,
    PERMISSIONS.FINANCIAL_AID_MANAGE,
    PERMISSIONS.SCHOLARSHIP_TYPES_VIEW,
    PERMISSIONS.SCHOLARSHIP_TYPES_CREATE,
    PERMISSIONS.SCHOLARSHIP_TYPES_UPDATE,
    PERMISSIONS.SCHOLARSHIP_TYPES_DELETE,
    PERMISSIONS.SCHOLARSHIP_TYPES_MANAGE,
    PERMISSIONS.RUBRICS_VIEW,
    PERMISSIONS.RUBRICS_CREATE,
    PERMISSIONS.RUBRICS_UPDATE,
    PERMISSIONS.RUBRICS_DELETE,
    PERMISSIONS.RUBRICS_MANAGE,
  ],
  CONTENT_MANAGER: [
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_MANAGE,
    PERMISSIONS.STORAGE_VIEW,
    PERMISSIONS.STORAGE_UPLOAD,
    PERMISSIONS.STORAGE_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.NEWSLETTER_VIEW,
    PERMISSIONS.NEWSLETTER_SEND,
  ],
  SUPPORT_STAFF: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.CONTENT_VIEW,
  ],
  STUDENT: [
    // Students have no admin permissions
  ],
}

// Resource-based permission groups
export const PERMISSION_GROUPS = {
  users: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE,
  ],
  domains: [
    PERMISSIONS.DOMAINS_VIEW,
    PERMISSIONS.DOMAINS_CREATE,
    PERMISSIONS.DOMAINS_UPDATE,
    PERMISSIONS.DOMAINS_DELETE,
    PERMISSIONS.DOMAINS_MANAGE,
  ],
  categories: [
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_UPDATE,
    PERMISSIONS.CATEGORIES_DELETE,
    PERMISSIONS.CATEGORIES_MANAGE,
  ],
  courses: [
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_DELETE,
    PERMISSIONS.COURSES_MANAGE,
  ],
  content: [
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_MANAGE,
  ],
  analytics: [
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
  ],
  settings: [
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  database: [
    PERMISSIONS.DATABASE_VIEW,
    PERMISSIONS.DATABASE_EXECUTE,
  ],
  audit: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
  ],
  payments: [
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_REFUND,
    PERMISSIONS.PAYMENTS_MANAGE,
  ],
  storage: [
    PERMISSIONS.STORAGE_VIEW,
    PERMISSIONS.STORAGE_UPLOAD,
    PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.STORAGE_MANAGE,
  ],
  support: [
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.SUPPORT_MANAGE,
  ],
  certificates: [
    PERMISSIONS.CERTIFICATES_VIEW,
    PERMISSIONS.CERTIFICATES_ISSUE,
    PERMISSIONS.CERTIFICATES_REVOKE,
    PERMISSIONS.CERTIFICATES_MANAGE,
  ],
  plans: [
    PERMISSIONS.PLANS_VIEW,
    PERMISSIONS.PLANS_CREATE,
    PERMISSIONS.PLANS_UPDATE,
    PERMISSIONS.PLANS_DELETE,
    PERMISSIONS.PLANS_MANAGE,
  ],
  newsletter: [
    PERMISSIONS.NEWSLETTER_VIEW,
    PERMISSIONS.NEWSLETTER_SEND,
    PERMISSIONS.NEWSLETTER_MANAGE,
  ],
  scholarships: [
    PERMISSIONS.SCHOLARSHIPS_VIEW,
    PERMISSIONS.SCHOLARSHIPS_CREATE,
    PERMISSIONS.SCHOLARSHIPS_UPDATE,
    PERMISSIONS.SCHOLARSHIPS_DELETE,
    PERMISSIONS.SCHOLARSHIPS_PUBLISH,
    PERMISSIONS.SCHOLARSHIPS_ARCHIVE,
    PERMISSIONS.SCHOLARSHIPS_MANAGE,
  ],
  applications: [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_REVIEW,
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_REJECT,
    PERMISSIONS.APPLICATIONS_MANAGE,
  ],
  awards: [
    PERMISSIONS.AWARDS_VIEW,
    PERMISSIONS.AWARDS_CREATE,
    PERMISSIONS.AWARDS_EDIT,
    PERMISSIONS.AWARDS_CANCEL,
    PERMISSIONS.AWARDS_MANAGE,
  ],
  sponsors: [
    PERMISSIONS.SPONSORS_VIEW,
    PERMISSIONS.SPONSORS_CREATE,
    PERMISSIONS.SPONSORS_UPDATE,
    PERMISSIONS.SPONSORS_DELETE,
    PERMISSIONS.SPONSORS_MANAGE,
  ],
  financialAid: [
    PERMISSIONS.FINANCIAL_AID_VIEW,
    PERMISSIONS.FINANCIAL_AID_CREATE,
    PERMISSIONS.FINANCIAL_AID_UPDATE,
    PERMISSIONS.FINANCIAL_AID_DELETE,
    PERMISSIONS.FINANCIAL_AID_MANAGE,
  ],
  scholarshipTypes: [
    PERMISSIONS.SCHOLARSHIP_TYPES_VIEW,
    PERMISSIONS.SCHOLARSHIP_TYPES_CREATE,
    PERMISSIONS.SCHOLARSHIP_TYPES_UPDATE,
    PERMISSIONS.SCHOLARSHIP_TYPES_DELETE,
    PERMISSIONS.SCHOLARSHIP_TYPES_MANAGE,
  ],
  rubrics: [
    PERMISSIONS.RUBRICS_VIEW,
    PERMISSIONS.RUBRICS_CREATE,
    PERMISSIONS.RUBRICS_UPDATE,
    PERMISSIONS.RUBRICS_DELETE,
    PERMISSIONS.RUBRICS_MANAGE,
  ],
} as const

// Check if user has permission based on role string
export function hasPermission(role: string, permission: Permission): boolean {
  const permissions = DEFAULT_ROLE_PERMISSIONS[role]
  if (!permissions) return false
  return permissions.includes(permission)
}

// Check if user has any of the given permissions
export function hasAnyPermission(role: string, permissions: Permission[]): boolean {
  return permissions.some(p => hasPermission(role, p))
}

// Check if user has all of the given permissions
export function hasAllPermissions(role: string, permissions: Permission[]): boolean {
  return permissions.every(p => hasPermission(role, p))
}